spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/content_scheduler
    username: ${PSG_USERNAME}
    password: ${PSG_PASSWORD}

twitter:
  bearer-token: ${TWITTER_BEARER_TOKEN}
  base-url: https://api.twitter.com
